apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-ui
  namespace: kube-system
  labels:
    app.kubernetes.io/name: edge-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: edge-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: edge-ui
    spec:
      serviceAccountName: edge-ui
      containers:
      - name: edge-api-server
        image: cnrancher/edge-api-server:master
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8443
          protocol: TCP
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/os
                operator: In
                values:
                - linux
