apiVersion: v1
kind: Service
metadata:
  name: edge-ui
  namespace: kube-system
  labels:
    app.kubernetes.io/name: edge-ui
spec:
  type: LoadBalancer
  ports:
  - port: 8443
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: edge-ui
