apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.edgeapi.cattle.io
  namespace: kube-system
spec:
  group: edgeapi.cattle.io
  version: v1alpha1
  names:
    kind: Foo
    plural: foos
    singular: foo
  scope: Namespaced
  subresources:
    status: {}
