apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: edge-ui
    app.kubernetes.io/version: 0.1.0
  name: rancher-edge-ui
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: edge-ui
    app.kubernetes.io/version: 0.1.0
  name: rancher-edge-ui-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: rancher-edge-ui
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: edge-ui
    app.kubernetes.io/version: 0.1.0
  name: rancher-edge-ui
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 8443
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: edge-ui
    app.kubernetes.io/version: 0.1.0
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: edge-ui
    app.kubernetes.io/version: 0.1.0
  name: rancher-edge-ui
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: edge-ui
      app.kubernetes.io/version: 0.1.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: edge-ui
        app.kubernetes.io/version: 0.1.0
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/os
                operator: In
                values:
                - linux
            weight: 1
      containers:
      - image: cnrancher/edge-api-server:master
        imagePullPolicy: Always
        name: edge-api-server
        ports:
        - containerPort: 8443
          name: http
          protocol: TCP
      serviceAccountName: rancher-edge-ui
