apiVersion: edgeapi.cattle.io/v1alpha1
kind: DeviceTemplate
metadata:
  name: my-template
  namespace: default
spec:
  deviceKind: ModbusDevice
  deviceVersion: v1alpha1
  deviceGroup: devices.edge.cattle.io
  deviceResource: modbusdevices
  labels:
    foo: bar
  templateSpec:
    protocol:
      tcp:
        ip: 127.0.0.1
        port: 502
        slaveID: 1
    properties:
      - name: temperature
        description: enable data collection of temperature sensor
        readOnly: false
        visitor:
          register: HoldingRegister
          offset: 2
          quantity: 8
        value: "33.3"
        dataType: float
