apiVersion: v1
kind: Service
metadata:
  name: edge-api-controller
  namespace: kube-system
  labels:
    app: edge-api-controller
spec:
  type: NodePort
  ports:
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app: edge-api-controller
