apiVersion: v1
kind: Service
metadata:
  name: edge-ui-backend
  labels:
    app: edge-ui-backend
spec:
  type: NodePort
  ports:
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app: edge-ui-backend
